title: From Visualization to Knowledge Discovery
subtitle: PASC 2026
author: Bernd Doser & Sebastian Trujillo-Gomez
# date: 2026/06/30
# date-format: "MMMM YYYY"
institute: Heidelberg Institute for Theoretical Studies (HITS)

execute:
  python: ".venv/bin/python"

format:
  revealjs:
    logo: images/HITS-Logo-negativ.png
    footer: "From Visualization to Knowledge Discovery (B. Doser & S. Trujillo-Gomez)"
    slide-number: true
    # show-slide-number: print
    
    highlight-style: a11y
    bibliography: references.bib
    width: 1300
    # template-partials:
    #   - title-slide.html
    menu: false

    theme: [default, custom.scss]
    auto-animate: true

    include-after-body: clean_title_page.html
    include-after: |
      <script type="text/javascript">
        Reveal.on('ready', event => {
          if (event.indexh === 0 || event.indexh === 1) {
            document.querySelector("div.has-logo > img.slide-logo").style.display = "none";
          }
        });
        Reveal.addEventListener('slidechanged', (event) => {
          if (event.indexh === 0) {
            Reveal.configure({ slideNumber: null });
            document.querySelector("div.has-logo > img.slide-logo").style.display = "none";
          } else if (event.indexh === 1) {
            Reveal.configure({ slideNumber: 'c' });
            document.querySelector("div.has-logo > img.slide-logo").style.display = "none";
          } else {
            Reveal.configure({ slideNumber: 'c' });
            document.querySelector("div.has-logo > img.slide-logo").style.display = null;
          }
        });
      </script>